In [4]:
import sys
!{sys.executable} -m pip install requests beautifulsoup4 pandas openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.31.0)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting pandas
  Downloading pandas-3.0.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/keetu/.local/lib/python3.11/site-packages (from beautifulsoup4) (4.16.0)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/keetu/.local/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /home/keetu/.local/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading pandas-3.0.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 49.1 MB/s  0:00:00eta 0:00:01
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading numpy-2.4.6-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 65.8 MB/s  0:00:00 eta 0:00:01
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: soupsieve, numpy, et-xmlfile, pandas, openpyxl, beautifulsoup4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [beautifulsoup4]m [openpyxl]
Successfully installed beautifulsoup4-4.15.0 et-xmlfile-2.0.0 numpy-2.4.6 openpyxl-3.1.5 pandas-3.0.3 soupsieve-2.8.4

In [ ]:
import requests

res= requests.get("https://boards-api.greenhouse.io/v1/boards/akunacapital/jobs")
print(res.status_code)

200

In [7]:
data=res.json()
type(data)
print(data.keys())
jobs_list= data['jobs']
jobs_list[0]

for i in jobs_list:
    if 'data' in i['title'].lower():
        print(i['title'])
        print(i['location']['name'])

dict_keys(['jobs', 'meta'])
Software Engineer - Data Engineering
Chicago, IL

In [8]:
print(jobs_list[3]['location'])
jobs_list[3]['absolute_url']

{'name': 'Chicago, IL'}

'https://www.akunacapital.com/careers/job/7496425/?gh_jid=7496425'

In [9]:
print(len(jobs_list))
for i in jobs_list:
    print(i['title'])

jobs_list[0].keys()

27
Akuna Capital’s 2026 Virtual Quant Trading Challenge
Akuna Capital's Talent Community
Broker Trader
Experienced Options Trader
Experienced Options Trader - SOFR
Floor Trader- SPX
Junior Quantitative Researcher - Prediction Markets
MLOps Engineer
MLOps Engineer
Network Engineer I
Performance Engineer
Platform Engineer
Project Manager
Quantitative Researcher
Quantitative Researcher - Prediction Markets
Quantitative Trader
Quant Strategist
Senior FPGA Engineer
Senior Systems Engineer
Senior Systems Engineer
Software Engineer - C++
Software Engineer - C++, Trading Strategies
Software Engineer - Data Engineering
Software Engineer - Python, Crypto
Systems Engineer
Systems Engineer
Systems Engineer

dict_keys(['absolute_url', 'data_compliance', 'internal_job_id', 'location', 'metadata', 'id', 'updated_at', 'requisition_id', 'title', 'company_name', 'first_published', 'language', 'application_deadline'])

In [4]:
import pandas as pd
# df = pd.DataFrame(big)
# print(df)

In [34]:
dfo= pd.read_excel('opt_friendly_compaines.xlsx')
print(dfo.head())
print(dfo.columns)

  Companies that hire students or recent graduates with CPT or OPT -This is a good list of companies to check out their open positions  \
0                                                 2U
1                                Abbott Laboratories
2                                             Accdon
3                                          Accenture
4                                 Adaptable Security

      Unnamed: 1
0       Maryland
1       Illinois
2  Massachusetts
3       New York
4     California
Index(['Companies that hire students or recent graduates with CPT or OPT -This is a good list of companies to check out their open positions', 'Unnamed: 1'], dtype='str')

In [37]:
import re

def cleaning_name(name):
    name = re.sub(r'\b(llc|ltd|inc|corp|co|lp|llp|pvt|limited|corporation|)\b','',name,flags=re.IGNORECASE).lower()

    name = re.sub(r'[^a-z0-9]', '', name) 
    return name

def get_data_jobs(slug):
    slug = cleaning_name(slug)
    url = f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs"
    res= requests.get(url)


    if res.status_code!=200:
        return []
    jobs_list = res.json()['jobs']
    matches=[]
    for i in jobs_list:
        if 'data' in i['title'].lower():
            matches.append({'company':slug,
                            'title':i['title'],
                            'location':i['location']['name'],
                            'url': i['absolute_url']

            
                            })
    return matches
    
get_data_jobs('Akuna Capital LLC')

[{'company': 'akunacapital',
  'title': 'Software Engineer - Data Engineering',
  'location': 'Chicago, IL',
  'url': 'https://www.akunacapital.com/careers/job/7496411/?gh_jid=7496411'}]

In [ ]:
slugs= dfo.iloc[:, 0].tolist()
big=[]
for s in slugs:

    results= get_data_jobs(s)
    big.extend(results)
print(big)

In [36]:
dfb= pd.DataFrame(big)
dfb.head(10)
#dfb.to_excel('opt_friendly_jobs.xlsx', index=False)

,company,title,location,url
0,2u,Data Scientist II,Crystal City,https://job-boards.greenhouse.io/2u/jobs/85510...
1,2u,Senior Data Product Manager,Crystal City,https://job-boards.greenhouse.io/2u/jobs/85490...
2,akunacapital,Software Engineer - Data Engineering,"Chicago, IL",https://www.akunacapital.com/careers/job/74964...
3,coinbase,"Senior Data Scientist, CX Analytics",Remote - USA,https://www.coinbase.com/careers/positions/800...
4,coinbase,"Senior Manager, Compliance Product Data",Remote - USA,https://www.coinbase.com/careers/positions/759...
5,coinbase,Senior Software Engineer - Data Platform,Remote - USA,https://www.coinbase.com/careers/positions/785...
6,coinbase,Senior Software Engineer - Data Platform,Remote - Canada,https://www.coinbase.com/careers/positions/781...
7,coinbase,"Senior Staff Software Engineer, Data Platform",Remote - USA,https://www.coinbase.com/careers/positions/771...
8,onetrust,Implementation Consultant (Privacy & Data Gove...,"Atlanta, Georgia",https://job-boards.greenhouse.io/onetrust/jobs...
9,onetrust,Principal Solutions Engineer - Data & AI Gover...,United States - Flex,https://job-boards.greenhouse.io/onetrust/jobs...

In [38]:
found = 0
not_found = 0

for s in slugs:
    slug = cleaning_name(s)
    url = f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs"
    res = requests.get(url)
    if res.status_code == 200:
        found += 1
    else:
        not_found += 1

print('On Greenhouse:', found)
print('Not found:', not_found)

On Greenhouse: 11
Not found: 203

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

In [11]:
df_info = pd.read_csv('Employer Information (1).csv', encoding='utf-16', sep='\t', low_memory=False,)
df_info.head(10)

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
0,1,2026,NaN,3227.0,"54 - Professional, Scientific, and Technical S...",CANTON,MI,48187.0,0,0,0,0,0,0,0,0,0,0,0,1
1,2,2026,NaN,4902.0,31-33 - Manufacturing,RANDOLPH,MA,2368.0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,2026,NaN,9012.0,31-33 - Manufacturing,HILLSBOROUGH,NH,3244.0,0,0,1,0,0,0,0,0,0,0,0,0
3,4,2026,1 ALPHA TECHNOLOGIES LLC,4511.0,"54 - Professional, Scientific, and Technical S...",HOUSTON,TX,77098.0,0,0,0,0,0,0,0,0,0,1,0,0
4,5,2026,1 DUST GROUP LLC,5330.0,"54 - Professional, Scientific, and Technical S...",FARMERS BRANCH,TX,75234.0,1,0,0,0,0,0,0,0,0,0,0,0
5,6,2026,1 EMC LLC,9142.0,72 - Accommodation and Food Services,FINDLAY,OH,45840.0,1,0,0,0,0,0,0,0,0,0,0,0
6,7,2026,1 NET SOFTWARE TECHNOLOGIES,9485.0,"54 - Professional, Scientific, and Technical S...",IRVING,TX,75063.0,0,0,0,0,0,0,0,0,0,0,1,0
7,8,2026,"1 WAY SOLUTIONS, INC.",3700.0,"54 - Professional, Scientific, and Technical S...",ATLANTA,GA,30062.0,0,0,0,0,0,0,0,0,1,0,0,0
8,9,2026,1-800-FLOWERS COM INC,7311.0,44-45 - Retail Trade,JERICHO,NY,11753.0,0,0,1,0,0,0,0,0,0,0,0,0
9,10,2026,1FINITY AMERICAS INC,4286.0,"54 - Professional, Scientific, and Technical S...",DALLAS,TX,75252.0,1,0,2,0,0,0,0,0,1,0,0,0

In [22]:
# print(df_info['Tax ID'].nunique())
# print(df_info['Tax ID'].value_counts())


print(df_info['Employer (Petitioner) Name'].nunique())

print(df_info['Employer (Petitioner) Name'].value_counts().sum())

# print(df_info['Industry (NAICS) Code'].value_counts().head(20))

69752
98978

In [23]:
unique_companies = df_info['Employer (Petitioner) Name'].dropna().unique()
print(len(unique_companies))

69752